### ISSUE TITLE
Clan 관리 기능

### ISSUE THREAD

**Issue by onepunch-tk** [onepunch-tk/runaway-bot#3]
## TODO
 
- [ ] 클랜원 등록/관리 (/클랜가입, /클랜탈퇴) 
- [ ] 클랜원 역할(role) 자동 부여 
- [ ] 클랜원 목록 조회 
- [ ] 클랜 규칙 안내
